version: '3.7'
networks:
  github:
    name: github
    driver: bridge

services:

  php:
    image: likesistemas/php-dev:${PHP_VERSION:-56}
    volumes:
      - ./:/var/www/public/
    networks:
      - github